version: "3.8"
services:
  db:
    image: postgres:16
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simplifica
    volumes:
      - ./postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: simplifica@ifal.edu.br
      PGADMIN_DEFAULT_PASSWORD: 1590753
    volumes:
      - ./pgadmin:/var/lib/pgadmin